services:

  api:
    build:
      context: .
      dockerfile: infra/docker/api/Dockerfile
    container_name: rag-api
    environment:
      - PYTHONPATH=/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
      - ./apps:/app/apps
      - ./database:/app/database
      - ./core:/app/core
      - ./tests:/app/tests
      - ./alembic:/app/alembic
      - ./alembic.ini:/app/alembic.ini
      - ./enums:/app/enums
      - ./config:/app/config
      - ./services:/app/services
      - ./tests:/app/tests
    restart: unless-stopped

  worker:
    build:
      context: .
      dockerfile: infra/docker/worker/Dockerfile
    container_name: rag-worker
    environment:
      - PYTHONPATH=/app
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./apps:/app/apps          # ← only mount source code
    restart: unless-stopped

  postgres:
    image: pgvector/pgvector:pg16
    container_name: rag-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/migrations/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  redis:
    image: redis:7
    container_name: rag-redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  neo4j:
    image: neo4j:5
    container_name: rag-neo4j
    environment:
      NEO4J_AUTH: ${NEO4J_USERNAME}/${NEO4J_PASSWORD}
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data
    restart: unless-stopped

  mlflow:
    image: ghcr.io/mlflow/mlflow:v3.1.0
    container_name: rag-mlflow
    ports:
      - "5001:5000"
    command: >
      mlflow server
      --host 0.0.0.0
      --port 5000
    volumes:
      - ./mlruns:/mlflow/mlruns

volumes:
  postgres_data:
  neo4j_data: